### PR TITLE
Update Nephele task names

### PR DESCRIPTION
**Pull request by fhueske**
- Names have prefix of Pact contract (Map, Red, Cmb, Mat, Crs, CGp, ...)
- All chained tasks are added to name of chain parent

Task names are only proposals. Let me know, if you prefer a different naming.

This pull request addresses #300

### CODE REVIEW

**Comment by rmetzger** [comment]
I'm not sure but I guess the full names are probably nicer: Map, Reduce, Compare, Cross.
Horizontal space is not a problem in the interface.

**Comment by fhueske** [comment]
You're probably right. Might be a bit unintuitive... 
Cmb was meant to be an abbreviation for Combine and not Compare ;-)

Other opinions?

**Comment by rmetzger** [comment]
Seems like I'm a bit tired. there is no compare operator ;)

**Comment by fhueske** [comment]
Alright, I'll extend the names.

**Comment by StephanEwen** [comment]
I am merging this for now, because of the pending code reorganization.

Asdding the names inside the operators that define properties (required/produced) is actually not the right place, as they have not a 1:1 correspondance to UDF operators. We should move that in the near future to a different place.

**Comment by fhueske** [comment]
I know, but this is the place where combiners are generated. Before that Reduce is just Reduce. 

We can extend the naming code with a check for the Contract type, but I thought right now there is a 1:1 relationship between strategies and contracts and omitted the check. Which contracts share strategies at the moment?

**Pull request merged**
