### PR TITLE
Fix tests failing with java 8 #457 

### PR DESCRIPTION
**Pull request by zentol**
Compatibility fixes for java 8, see #457.

Note: preliminary version, this is mostly to see whether i found all issuess

### CODE REVIEW

**Comment by zentol** [comment]
looks like compiling on java8 works fine.

only issue remaining is that using -Xdoclint:none breaks previous versions of java.
(it prevent errors from malformed javadoc comments)

**Comment by rmetzger** [comment]
Mh. Another user on Stackoverflow has the same issue we do: http://stackoverflow.com/a/16743137/568695

I have no idea what to do in this case.

**Comment by zentol** [comment]
looks like it works. :)

**Comment by rmetzger** [comment]
How did you resolve it?

**Comment by StephanEwen** [comment]
We have a regular javadoc build plugin now and one conditionally for java 8 that overrides the regular one?

**Comment by zentol** [comment]
@StephanEwen correct.

**Comment by StephanEwen** [comment]
God job :-)

Out of curiosity, what is the javassist dependency for?

**Comment by zentol** [comment]
there's a transitive dependency in stratosphere-core for a javaassist version that is not compatible with java 8. guess i could encapsulate it as well in an extra profile.

**Comment by StephanEwen** [comment]
Okay. Can you solve it with the dependency management entries? I think that would be the "clean" way to do it.

Is that dependency actually used? Or is it a dependency that for example hadoop adds that is never used, because we only use hadoop's hdfs client?

**Comment by zentol** [comment]
Ill add it to the dependency management.

i checked the dependendies again; javaassist actually comes up in multiple parts.
(clients, runtime and addons aswell)

maven marks it as used in clients and runtime.

**Comment by rmetzger** [comment]
I think the pull request is good to merge.

**Comment by StephanEwen** [comment]
Should we exclude one of the Java7 profiles? With Hadoop 1 and 2, we now have 8 builds to test. How about we test
- oraclejdk8
- oraclejdk7
- openjdk6

**Comment by fhueske** [comment]
Agree :+1:

**Comment by rmetzger** [comment]
@zentol Can you update the `.travis.yml` and remove the `openjdk7` ?
Then I'll merge your PR.

**Comment by zentol** [comment]
@rmetzger Done.

**Comment by rmetzger** [comment]
Merged in 6bf7d5a2451f9fd0b1773a51785b24f7aeb83304

**Pull request closed without merging**
