### PR TITLE
More generated Tuples up to 25.

### PR DESCRIPTION
**Pull request by twalthr**
I had a use case where I needed 24-tuples. @qmlmoon also needed a larger arity for the testjob. 
(I can't find the issue with the discussion at the moment.)

I think 25 is a nice number.

This PR also corrects a small issue of the TupleGenerator together with the new checkstyle.

### CODE REVIEW

**Comment by twalthr** [comment]
I introduced the possibility to skip the checkstyle for specific regions. The syntax is as follows:

``` java
//CHECKSTYLE.OFF: AvoidStarImport - Needed for TupleGenerator
import eu.stratosphere.api.java.tuple.*;
//CHECKSTYLE.ON: AvoidStarImport
```

The developer can only disable one module at a time and must leave a comment, why he/she disables the checkstyle module.

**Comment by StephanEwen** [comment]
Is it actually possible to create a checkstyle rule to allow the import of `eu.stratosphere.api.java.tuple.*` ?

**Comment by StephanEwen** [comment]
Will merge now. Let's keep looking for the exception rule

**Comment by StephanEwen** [comment]
Merged in 5b34bef7dba5c3842059a934e1c00d7c32e40979

**Pull request closed without merging**
