### PR TITLE
Add PojoTypeInformation, PojoComparator and Expressions for Keys

### PR DESCRIPTION
**Pull request by aljoscha**

### CODE REVIEW

**Comment by StephanEwen** [comment]
Should we merge this now? I think the general tendency is to include this in 0.6, and not in 0.5  What do you think?

**Comment by fhueske** [comment]
I would not add it to the 0.5 feature list.

**Comment by StephanEwen** [comment]
@aljoscha Is this pull request still valid, or is it out of sync with the feature dev already?

**Comment by aljoscha** [comment]
I'm not sure. It works, but is limited and slow because the comparators use introspection to get at the data.

**Comment by StephanEwen** [comment]
We move the feature to 0.6 anyways, to that is fin. We will not merge it as of now. 0.5 is feature frozen ;-)

**Comment by aljoscha** [comment]
Superseded by #908

**Pull request closed without merging**
