### PR TITLE
Remove IPv4 Stack Hint (issue #189)

### PR DESCRIPTION
**Pull request by uce**
See @StephanEwen's comments in #189.

These were all references to the IPv4 stack I found.

### CODE REVIEW

**Comment by StephanEwen** [comment]
Before we can merge this, we need to test whether cluster setups are affected. The discovery manager is important for task managers to find their job-manager-facing ip address. We should also let the os or jvm determine the network stack (ip v4 or ip v6) and not force anything, because that may  prohibit the system to work in certain settings. If I recall correctly, the discovery manager needed ip v4 for broadcast announcements of the job managers address in cloud settings where no slave file was available, but we don't want to go that route.

**Comment by uce** [comment]
OK, sure. Then we should keep the system property check in `DiscoveryService`, no? Both
- `java.net.preferIPv4Stack`, and
- `java.net.preferIPv6Addresses`

are set by the OS, right?

The [docs](http://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html) say:

> java.net.preferIPv4Stack (default: false)
> If IPv6 is available on the operating system the underlying native socket will be, by default, an IPv6 socket which lets applications connect to, and accept connections from, both IPv4 and IPv6 hosts. However, in the case an application would rather use IPv4 only sockets, then this property can be set to true. The implication is that it will not be possible for the application to communicate with IPv6 only hosts.
> 
> java.net.preferIPv6Addresses (default: false)
> When dealing with a host which has both IPv4 and IPv6 addresses, and if IPv6 is available on the operating system, the default behavior is to prefer using IPv4 addresses over IPv6 ones. This is to ensure backward compatibility, for example applications that depend on the representation of an IPv4 address (e.g. 192.168.1.1). This property can be set to true to change that preference and use IPv6 addresses over IPv4 ones where possible.

I think I would go with the `java.net.preferIPv6Addresses` check.

Or is there another way?

**Comment by StephanEwen** [comment]
Do we need such flags at all? If we do not use that one specific feature of the discovery service, is there anything left that is IPv4 or IPv6 aware or dependent? I think we should be able to write the "get my public IP" functionality such that it works with both v4 and v6 transparently.

**Comment by uce** [comment]
OK, now I see what you're getting at. I didn't have a close look :eyes: at the `DiscoveryService`, but what you describe (transparent "get my public IP") makes sense.

**Comment by StephanEwen** [comment]
Since the code paths in the discovery service that require the flag are inactive anyways, I will merge this now.
We will follow up on this with issue #18

**Comment by StephanEwen** [comment]
Merged in 361e469bb9ac742bd3c2ddaf930cdebe160300f1

**Pull request closed without merging**
