### PR TITLE
fix NullPointException in web interface when inspecting a job immediately after it finished

### PR DESCRIPTION
**Pull request by qmlmoon**
issue #464

### CODE REVIEW

**Comment by markus-h** [comment]
Where exactly did this NullPointerException occur? Is events null? Because we're iterating over it at two places.
If I understand your fix correctly you are iterating now fully over jobmanager.getOldJobs() and thereby writing out all state changes of all archived jobs. That produces a lot of network overhead because we are only intersted in the state changes of one specific job.

**Comment by rmetzger** [comment]
@markus-h Are your concerns addressed by the last commit? (So is the PR ready to merge?)

**Comment by markus-h** [comment]
Yes it is addressed and can be merged.
For the future I'm still not sure if the new solution is a good one. 8 secs wait time is really long. Perhaps we should think about a better solution at some time.

**Comment by rmetzger** [comment]
So the refresh-rate of the interface (also for running jobs?) has been set to 8 seconds with this pull request?

**Comment by qmlmoon** [comment]
No. Only for the job that is finished, it will be shown in the job history
8 secs later after it finishes

2014-02-26 19:21 GMT+01:00 Robert Metzger notifications@github.com:

**Comment by StephanEwen** [comment]
Merged in 7aacbf3994cca859d4097ebea117934899a7b684

**Pull request closed without merging**
