### PR TITLE
Scala examples for Triangle Enumeration

### PR DESCRIPTION
**Pull request by fhueske**
Added first versions of the Scala examples for triangle enumeration.
The examples include:

```
Annotation of edges with the corresponding vertex degrees (+ unique projection of vertexes and duplicate removal)
Enumeration of triangles on edges with degrees.
```

The examples perform the same job as the corresponding Java versions. However, they use different strategies (joins instead of reduce in some places). Exactly following the Java strategies didn't work for a Scala novice ;-)
However, this might be changed later.

### CODE REVIEW

**Comment by aljoscha** [comment]
Looks good. Could you also add tests similar to the KMeansIterativeITCase and friends?

**Comment by aljoscha** [comment]
Was it hard to figure out how to do stuff, by the way?

**Comment by fhueske** [comment]
The solution I committed was easy to implement. I also tried to follow more closely the Java version but could not do it.

I have a couple remarks, that will share with you after the weekend. But overall a very nice work!

I suggest that the other examples are also done by people that haven't used the Scala frontend yet. That should get you more feedback.

**Comment by aljoscha** [comment]
Yes, I agree. Plus it's less work for me ... :smile:

**Comment by fhueske** [comment]
I prepared integration tests for the example jobs but they fail due to some missing Scala class. This seems to be some integration issues. The example jobs themselves are working.
I'm waiting for a fix/hint from @aljoscha to merge them together with the tests.

**Comment by fhueske** [comment]
Integration tests should work now. 
Let's wait for Travis and merge if all tests pass.

**Comment by aljoscha** [comment]
@fhueske You added the additional dependency on scala-reflect. Was that what fixed the weird TypeCreator error we saw?

**Comment by fhueske** [comment]
@aljoscha Yes, that solved the problem. 
I did not further investigate the issue after the bug was fixed. Do you see any problems with the added dependency?

**Comment by aljoscha** [comment]
Nah, I don't see a problem with that.

**Pull request merged**
