### PR TITLE
Release 0.4

### PR DESCRIPTION
**Pull request by wilsoncao**
I am applying for the New Example Jobs / Development of a Stratosphere Standard Library with common operators.

### CODE REVIEW

**Comment by rmetzger** [comment]
Hi,

why did you create a pull request of a release branch to our main branch?

Pull requests exist to offer your changes to our code. For a successful GSoC application, we expect you to write code for our system.
The easiest way for you to give us the code you've written is a pull request.
More information:
http://oss-watch.ac.uk/resources/pullrequest
https://help.github.com/articles/using-pull-requests

**Comment by wilsoncao** [comment]
Hi,

   I am sorry to make a mistake. And I am wondering whether I can pull request after the proposal deadline? Because recently I am busy with my TOEFL exam and maybe don't have much time to write the code.

Yours,
Wilson Cao

------------------ 原始邮件 ------------------
发件人: "Robert Metzger";notifications@github.com;
发送时间: 2014年3月16日(星期天) 晚上10:36
收件人: "stratosphere/stratosphere"stratosphere@noreply.github.com; 
抄送: "275239608"275239608@qq.com; 
主题: Re: [stratosphere] Release 0.4 (#595)

Hi,

why did you create a pull request of a release branch to our main branch?

Pull requests exist to offer your changes to our code. For a successful GSoC application, we expect you to write code for our system.
 The easiest way for you to give us the code you've written is a pull request.
 More information:
http://oss-watch.ac.uk/resources/pullrequest
https://help.github.com/articles/using-pull-requests

**Comment by StephanEwen** [comment]
I am closing this one as a confused pull request.

**Comment by rmetzger** [comment]
@wilsoncao: Regarding your question: As Fabian said on the mailing list, we can not make any exceptions to this deadline. Google will not accept late proposals for any reason and we want to start reviewing the applications once the deadline is over.

**Pull request closed without merging**
