### PR TITLE
Add PojoTypeInformation, PojoComparator and Expressions for Keys

### PR DESCRIPTION
**Pull request by aljoscha**
This enables code like:

``` java
class WC {
    public String word;
    public int count;
}
...
DataSet<WC> result = tokenized
        .groupBy("word")
        .reduce(new ReduceFunction<WC>() {
            public WC reduce(WC value1, WC value2) {
                return new WC(value1.word, value1.count + value2.count);
            }
        });
```

### CODE REVIEW

**Comment by rmetzger** [comment]
Amazing! Whats the plan regarding unit tests for that?

**Comment by aljoscha** [comment]
We should have some, but this is still an early implementation. I could add a WordCountITCase and a RelQuery using this feature with an ITCase.

**Comment by StephanEwen** [comment]
I think the type mapping also needs quite a few "Unit" tests, meaning
testing different scenarios independent of program execution.

**Comment by aljoscha** [comment]
Make new pull request from pojo-feature branch.

**Pull request closed without merging**
