### PR TITLE
Design and Typo Fixes

### PR DESCRIPTION
**Pull request by uce**
- Removes the white bar
- Corrects navbar markup
- Fixes typo on frontpage
- Fixes scrollong on people page

With the help of @rmetzger. Thx!

### CODE REVIEW

**Comment by rmetzger** [comment]
You can preview the changes here: http://robertmetzger.de/ozone/

**Comment by aljoscha** [comment]
I liked the old primary color and font. But maybe that's just me.

**Comment by uce** [comment]
The preview is not working for me.

I liked the nav bar color more before, but I think the link colors are better now.

We could also use the same old theme (for the navbar) and overwrite the link colors in the main part. Would that be better for you @aljoscha? If others think the same way, we should go for it.

**Comment by rmetzger** [comment]
I just renamed my repo, so you have to use this url: http://robertmetzger.de/stratosphere/

There are some things that I like about the new design: the font sizes are better. you can differentiate between h1 and h2.
It seems that this layout works better with our website, than the previous one.

**Comment by StephanEwen** [comment]
Looks good.

One comment: I liked the shade at the bottom edge of the image in the old design. Kind of acts as a separator between the parts of the page. Is it hard to add that back?

**Comment by rmetzger** [comment]
No. I think it is this part of the main.css

``` css
.jumbotron {
[...]
      box-shadow: 0 3px 7px rgba(0, 0, 0, 0.2) inset, 0 -3px 7px rgba(0, 0, 0, 0.2) inset;
```

**Comment by uce** [comment]
I added the shadow back in with a new commit (which doesn't appear here yet... any idea why?). It's exactly what @rmetzger has written (but not in .jumbatron but .masthead.. except we really want it for all jumbatrons).

I also added some more emphasize to the active page in the navbar (it's bold now... in the old theme it had a different background color).

I noticed a **bug**: the highlighting script in the documentation page breaks the highlighting of the active page, e.g. the "Documentation" nav point is not highlighted even if it's active.

**Comment by rmetzger** [comment]
There is also a bug on the event page: Just scroll down, you'll see it

**Comment by uce** [comment]
There is also a problem on the people page with the subnav. When  you directly click the sublinks, the previous one gets highlighted. What should we do about it?

I've added another commit to properly center the jumbatron images.

**Comment by StephanEwen** [comment]
Some comments for the quickstart page (there are also typos on the current page):

Change heading: What do you want to do? --> What would you like to do?

There is the general question if we want to refer to the programs as **Jobs** or as **Stratosphere Programs**. I have a slight bias towards the second option.

The sentence below the heading:
_"There are plenty of ways to start using Stratosphere. Install it, if you want to get to know the infrastructure. Application developers should start immediately with their favorite programming language."_
could be changed to
_"There are plenty of ways to explore Stratosphere. Install it one one or more machines, if you want to get to know the infrastructure. Application developers can also start immediately with their favorite programming language and run programs locally from within their favorite IDE."_

Under the Install Link:
_"Install on your computer or on a cluster to run jobs."_ --> "Install on your computer or on a cluster of machines to run Stratosphere programs distributed."

Under the Scala Link:
Develop Stratosphere programs with Scala [maybe link to Scale here?] and experience Stratosphere's new easy, concise, and flexible programming abstraction. Run and debug your programs locally.

Under the JavaLink:
Write Stratosphere programs with the classic Java API. Run and debug your programs locally.

Any thoughts?

**Comment by fhueske** [comment]
I mainly agree with Stephan's proposal and have a few additional remarks.

I would say, you implement a Stratosphere program but you execute a Stratosphere job (basically job = program "instantiation" with parameters). Not sure if the difference is to subtle though...

How about "Install Stratosphere on one or more computers" for the install link. The current and proposed versions are quite bulky in my opinion.

For the Scala text, I would drop "easy" and "flexible". Not because it is not easy and flexible but four attributes are too much and new and concise are the most appealing ones from my point of view.

**Pull request merged**
