### PR TITLE
pre-release test

### PR DESCRIPTION
**Pull request by physikerwelt**
this is not an actual release
it's just a test how releases can be realized technically

### CODE REVIEW

**Comment by physikerwelt** [comment]
Caution: Do not merge to master.

**Comment by rmetzger** [comment]
Can you move the change version script into `/tools` ?

@StephanEwen: What I told you yesterday with automatic sonatype deployment is only partially true.
It will deploy the "normal" Stratosphere with Hadoop 1.2.1 as a dependency. But the script that prepares the Hadoop Yarn build will fail. The first line of the script `deploy_to_maven.sh` contains two variables with the version numbers. 
I think it is an easy fix to extract the version number from the main pom, for the second variable, I would just append `-hadoop02` 
Note: the hadoop yarn version must contain the string `-hadoop02`.

**Comment by physikerwelt** [comment]
@rmetzger @StephanEwen do I have to do something for this?

**Comment by rmetzger** [comment]
I'm going to do it. Its only 5 mins for me

**Comment by rmetzger** [comment]
Okay, 16 Minutes.
@StephanEwen can you wait until https://github.com/stratosphere/stratosphere/pull/223 has been successfully build on Travis. Make sure that it correctly detects the version of Stratosphere (should be one of the last lines in the travis log). If this is the case, merge https://github.com/stratosphere/stratosphere/pull/223 into the master, rebase this pull request (so that the new script is also applied to the branch of this version. Then you can push this PR into a new branch.

**Comment by physikerwelt** [comment]
local or jenkins testing takes 3 minutes ... compared to that Travis is somehow slow... I asked at the travis channel at freenode... a local travis installation is not recommended. I think we should provide some best practice for developers how to deal with the slow build time

**Comment by rmetzger** [comment]
It is impossible to build and verify in 3 minutes. My Core i7 (3.6 ghz or so on one core) machine here with 16 gb main memory needs around 15 mins (I will test that now to see the exact time).

Remember also that Travis has to download all dependencies from maven.
We use travis because we don't want to spend more than 15 seconds per pull request and push with building and verification. If we would run our own server, we would almost certainly spend much more time with the setup. 
Our core competency is developing software, not building good infrastructure.

**Comment by physikerwelt** [comment]
ok. I was running package only (as stated in the readme)
dopa-vm/stratosphere-dev$ mvn package

[INFO] Reactor Summary:
[INFO]
[INFO] stratosphere ...................................... SUCCESS [0.512s]
[INFO] nephele ........................................... SUCCESS [0.006s]
[INFO] nephele-common .................................... SUCCESS [5.059s]
[INFO] nephele-management ................................ SUCCESS [0.284s]
[INFO] nephele-server .................................... SUCCESS [1.927s]
[INFO] nephele-profiling ................................. SUCCESS [1.583s]
[INFO] nephele-queuescheduler ............................ SUCCESS [0.261s]
[INFO] nephele-clustermanager ............................ SUCCESS [6.383s]
[INFO] nephele-hdfs ...................................... SUCCESS [0.078s]
[INFO] nephele-s3 ........................................ SUCCESS [0.347s]
[INFO] nephele-visualization ............................. SUCCESS [0.074s]
[INFO] nephele-examples .................................. SUCCESS [0.176s]
[INFO] pact .............................................. SUCCESS [0.010s]
[INFO] pact-common ....................................... SUCCESS [2.674s]
[INFO] pact-array-datamodel .............................. SUCCESS [0.033s]
[INFO] pact-runtime ...................................... SUCCESS [1:15.631s]
[INFO] pact-compiler ..................................... SUCCESS [0.613s]
[INFO] pact-clients ...................................... SUCCESS [1.095s]
[INFO] pact-examples ..................................... SUCCESS [0.444s]
[INFO] pact-scala ........................................ SUCCESS [0.208s]
[INFO] pact-scala-core ................................... SUCCESS [0.641s]
[INFO] pact-scala-examples ............................... SUCCESS [0.858s]
[INFO] pact-tests ........................................ SUCCESS [10.873s]
[INFO] stratosphere-dist ................................. SUCCESS [4.735s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:54.875s
[INFO] Finished at: Tue Oct 29 21:55:22 CET 2013
[INFO] Final Memory: 27M/236M
... I'll try clean verify as comparison

**Comment by rmetzger** [comment]
18 Minutes. So travis is actually quite okay, given that they have to download more than 80 MB first, and some workers also upload the artifacts to different servers!

```
[INFO] Reactor Summary:
[INFO] 
[INFO] stratosphere ...................................... SUCCESS [0.841s]
[INFO] nephele ........................................... SUCCESS [0.020s]
[INFO] nephele-common .................................... SUCCESS [8.864s]
[INFO] nephele-management ................................ SUCCESS [0.738s]
[INFO] nephele-server .................................... SUCCESS [34.086s]
[INFO] nephele-profiling ................................. SUCCESS [2.280s]
[INFO] nephele-queuescheduler ............................ SUCCESS [0.512s]
[INFO] nephele-clustermanager ............................ SUCCESS [6.646s]
[INFO] nephele-hdfs ...................................... SUCCESS [0.302s]
[INFO] nephele-s3 ........................................ SUCCESS [4.660s]
[INFO] nephele-visualization ............................. SUCCESS [0.435s]
[INFO] nephele-examples .................................. SUCCESS [0.296s]
[INFO] pact .............................................. SUCCESS [0.016s]
[INFO] pact-common ....................................... SUCCESS [10.776s]
[INFO] pact-array-datamodel .............................. SUCCESS [0.100s]
[INFO] pact-runtime ...................................... SUCCESS [4:43.413s]
[INFO] pact-compiler ..................................... SUCCESS [1.396s]
[INFO] pact-clients ...................................... SUCCESS [1.564s]
[INFO] pact-examples ..................................... SUCCESS [0.495s]
[INFO] pact-scala ........................................ SUCCESS [0.350s]
[INFO] pact-scala-core ................................... SUCCESS [42.165s]
[INFO] pact-scala-examples ............................... SUCCESS [34.659s]
[INFO] pact-tests ........................................ SUCCESS [10:40.035s]
[INFO] stratosphere-dist ................................. SUCCESS [9.582s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18:04.589s
[INFO] Finished at: Tue Oct 29 22:01:43 CET 2013
[INFO] Final Memory: 42M/230M
[INFO] ------------------------------------------------------------------------
mvn clean verify  1039.18s user 125.37s system 107% cpu 18:05.89 total
```

**Comment by physikerwelt** [comment]
18 minutes seems quite a lot. considering an average of 3 attempts (maybe others need less attempts) leads to 40 minutes of waiting time before submitting something. This does not motivate people to commit atomic changes.
I played with maven configurations like `<parallel>classes</parallel>` and  `<useUnlimitedThreads>true</useUnlimitedThreads>` but it seems that are a lot of dependencies between the tests... If there is no best practice, I'll create an issue for that.

**Comment by rmetzger** [comment]
You should use eclipse to see errors immediately.
I'm not sure if running tests in parallel does help us because it could actually introduce more errors (its a distributed system that starts servers on ports etc. you can't do that in parallel)

I'm against running the tests in parallel.

**Comment by physikerwelt** [comment]
There are some IDEs like eclipse that help you to verify your code. However, for code validation they help little.
I think for the average JAVA programmer it's unlikely to write a program that does what he want's without testing it. (Even if a IDE like eclipse is used.)
Unit tests aim to design the smallest testable unit of the a software. I claim that one can start servers in parallel:-)
I recommend to run the tests locally, before submitting pull requests. (I used package rather than verify before.) However, running tests that take 18 Minutes is clearly not acceptable for local testing.
Not running all tests locally, makes it harder to determine why tests have failed.
E.g. Travis could not download jars from Sonatype on monday (HTTP 502). Restarting the build solved the problem.

**Comment by fhueske** [comment]
@physikerwelt 
I agree that 18 mins build time on current hardware (and 30 mins on my machine) are quite a lot and that it would be nice to reduce that.
However, Stratosphere is a complex system which requires extensive testing. It was a significant effort to get all these tests into place and I think that we rather need to extend testing (esp. for the optimizer and distributed settings) than stripping it down. 

One thing that will not happen in any case is to reduce test coverage! However, reducing tests while keeping the coverage at the same level, requires a lot of effort and more time than we have right row. We have more pressing issues and I do not see this as an urgent or even important problem that needs to be addressed at the moment.

Although, if you find an easy way to reduce build and test time for example by running tests in parallel, go for it and many people including myself will appreciate it a lot.

**Comment by rmetzger** [comment]
You merged the pull request into the wrong branch

And you forgot to apply my pull request first

**Comment by StephanEwen** [comment]
I did not mean to merge. Not sure what happened. I was trying to reply. Fat
fingers?
Am 30.10.2013 11:07 schrieb "Robert Metzger" notifications@github.com:

**Comment by StephanEwen** [comment]
Can you undo?
Am 30.10.2013 11:10 schrieb "Stephan Ewen" ewenstephan@gmail.com:

**Comment by rmetzger** [comment]
I'm not sure if undoing history is a good idea here?
I think another commit reverting the change is the cleaner solution.

**Comment by rmetzger** [comment]
https://github.com/blog/1642-merge-pull-requests-from-your-phone

**Comment by fhueske** [comment]
If you're fast enough, nobody will notice... Hurry up! :-D 
_justJoking_

**Comment by rmetzger** [comment]
No joking. I nuked our history!

**Comment by physikerwelt** [comment]
@rmetzger yes please undo... the pull request was not designed to be merged.. can you create a new branch so that I can make a propper pull request

**Comment by rmetzger** [comment]
Yes, I'm going to push it correctly now.

**Comment by physikerwelt** [comment]
thx

**Comment by rmetzger** [comment]
Okay. History has been changed.
I merged https://github.com/stratosphere/stratosphere/pull/223 (no rebase, stupid webinterface merge)
Created new branch with release version. https://github.com/stratosphere/stratosphere/tree/release-0.4-alpha.0

Now, we just have to wait for Travis.

**Comment by rmetzger** [comment]
The drama is not yet over. I'm having a minor issue with the deploy tool. Should be fixed by now

**Comment by rmetzger** [comment]
I will backport the hotfix to master once I verified it. I will also add the renaming tool to the master.

**Comment by StephanEwen** [comment]
Thanks, Robert, for fixing this!

**Comment by rmetzger** [comment]
"mvn deploy" pushed the artifact into the release staging area of Maven Central.
I'll look up if there is an easy way to release to maven central (please interrupt me, if this is not intended)

**Comment by physikerwelt** [comment]
I had a discussion about that with Kostas in June. Please ask him before submitting to maven central.

**Comment by rmetzger** [comment]
I appended `-SNAPSHOT`  in the release branch to deploy it to the snapshots repo.

**Pull request merged**
