### PR TITLE
(Re)add TransitiveClosureNaive, fix join, add ITCase

### PR DESCRIPTION
**Pull request by aljoscha**
Scala Join took left key selector for both sides of join. Re-enable
union. TransitiveClosureNaive uses union, this is tested in the ITCase.

Properly disable GlobalSchemaGenerator, the information it created has
not been used, only local field positions have been used.

### CODE REVIEW

**Comment by aljoscha** [comment]
@StephanEwen  I could not think of an example where union fails, since we only use local positions and I completely disabled the "global schema generator".

**Comment by StephanEwen** [comment]
Okay, very good. I will merge this soon.

**Comment by StephanEwen** [comment]
I am getting errors in the integration tests.

```
eu.stratosphere.types.KeyFieldOutOfBoundsException: Field 1 is accessed for a key, but out of bounds in the record.
    at eu.stratosphere.pact.runtime.plugable.pactrecord.RecordComparator.hash(RecordComparator.java:199)
    at eu.stratosphere.pact.runtime.shipping.RecordOutputEmitter.hashPartitionDefault(RecordOutputEmitter.java:145)
    at eu.stratosphere.pact.runtime.shipping.RecordOutputEmitter.selectChannels(RecordOutputEmitter.java:114)
    at eu.stratosphere.pact.runtime.shipping.RecordOutputEmitter.selectChannels(RecordOutputEmitter.java:23)
    at eu.stratosphere.nephele.io.RuntimeOutputGate.writeRecord(RuntimeOutputGate.java:259)
    at eu.stratosphere.nephele.io.AbstractRecordWriter.emit(AbstractRecordWriter.java:92)
    at eu.stratosphere.pact.runtime.shipping.RecordOutputCollector.collect(RecordOutputCollector.java:77)
    at eu.stratosphere.pact.runtime.shipping.RecordOutputCollector.collect(RecordOutputCollector.java:29)
    at eu.stratosphere.examples.scala.relational.WebLogAnalysis$$anon$18.map(WebLogAnalysis.scala:105)
    at eu.stratosphere.examples.scala.relational.WebLogAnalysis$$anon$18.map(WebLogAnalysis.scala:105)
    at eu.stratosphere.pact.runtime.task.chaining.ChainedCollectorMapDriver.collect(ChainedCollectorMapDriver.java:71)
    at eu.stratosphere.examples.scala.relational.WebLogAnalysis$$anon$17.map(WebLogAnalysis.scala:105)
    at eu.stratosphere.examples.scala.relational.WebLogAnalysis$$anon$17.map(WebLogAnalysis.scala:105)
    at eu.stratosphere.pact.runtime.task.chaining.ChainedCollectorMapDriver.collect(ChainedCollectorMapDriver.java:71)
    at eu.stratosphere.examples.scala.relational.WebLogAnalysis$$anon$13.map(WebLogAnalysis.scala:90)
    at eu.stratosphere.examples.scala.relational.WebLogAnalysis$$anon$13.map(WebLogAnalysis.scala:90)
    at eu.stratosphere.pact.runtime.task.chaining.ChainedCollectorMapDriver.collect(ChainedCollectorMapDriver.java:71)
    at eu.stratosphere.pact.runtime.task.DataSourceTask.invoke(DataSourceTask.java:168)
    at eu.stratosphere.nephele.execution.RuntimeEnvironment.run(RuntimeEnvironment.java:345)
    at java.lang.Thread.run(Thread.java:744)
```

**Comment by aljoscha** [comment]
Yes I did too. Disabling the global schema generator made a bug appear. For some reason (my oversight) join and coGroup did not correctly set the keys retrieved from the key selectors. But now it works, travis only failed in some cleanup test in one of the 6 different verify runs.

**Comment by StephanEwen** [comment]
Merged in 799f7a9f64d6b06b1bf73749f273e4759218c317

**Pull request closed without merging**
