### PR TITLE
Fix typo on startpage and make sub headlines bold

### PR DESCRIPTION
**Pull request by uce**
1. @cboden noticed a typo on the front page: **constrainT MapReduce interface** should be **constrainED MapReduce interface**.
2. I've also put more emphasis on the headlines, which makes it imho easier to navigate the page.

### CODE REVIEW

**Comment by rmetzger** [comment]
Preview http://robertmetzger.de/stratosphere/ (with https://github.com/stratosphere/stratosphere/pull/290)

I don't like the `<hr>` (the line) below the headlines.?
You are separating the headline from its content? That does not make much sense to me.

**Comment by uce** [comment]
Ah, sorry. I also had a preview. Forgot to post it.

This is the default CSS element for page headers, e.g. css class `.page-header`.

http://getbootstrap.com/components/#page-header

PS: putting an element like `hr` _by hand_ (to indicatae separate content) wouldn't make sense, but the line now actually is just layout and has no semantics (like separating content).

**Comment by rmetzger** [comment]
Yes, but this is for the page header. Here, we have only a subheading.

And still, I don't like it ;)

On Wed, Nov 27, 2013 at 7:00 PM, Ufuk Celebi notifications@github.comwrote:

> Ah, sorry. I also had a preview. Forgot to post it.
> 
> This is the default CSS element for page headers, e.g. css class
> .page-header.
> 
> http://getbootstrap.com/components/#page-header
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/stratosphere/stratosphere/pull/304#issuecomment-29406001
> .

## 

Robert Metzger, Kontakt: metzgerr@web.de, Mobil: 0171/7424461

**Comment by fhueske** [comment]
I agree with Robert here.
I would have hr above the headline to have the individual sections clearly separated.
Otherwise a section's content and the headline of the next section form a visual block.

**Comment by uce** [comment]
I agree (in this case :bowtie:). The preview at http://uce.github.io/ should be up to date any minute.

**Comment by StephanEwen** [comment]
Are you merging this?

**Pull request merged**
