### PR TITLE
Make sure progress bar label is visible by making the minimum width to 20%

### LINKED ISSUE #853: Web interface: task number not readable with low tasks counts
The number of tasks per execution stage is not readable with low task counts, i.e. if you have stragglers as in the screenshot below, it's hard to see if there is any progress at all.

screen shot 2014-05-24 at 18 06 10

### PR DESCRIPTION
**Pull request by vikhyat**
Fixes #853.

### CODE REVIEW

**Comment by rmetzger** [comment]
Thanks alot, very cool. I'll test the fix tomorrow and merge it.

Sent from my iPhone

On 27.05.2014, at 16:24, Vikhyat Korrapati notifications@github.com wrote:

## Fixes #853 https://github.com/stratosphere/stratosphere/issues/853.

You can merge this Pull Request by running

  git pull https://github.com/vikhyat/stratosphere progress-bar-labels

Or view, comment on, or merge it at:

  https://github.com/stratosphere/stratosphere/pull/876
Commit Summary
- Make sure progress bar label is visible by making the minimum width to
  20%.

File Changes
- _M_
  stratosphere-runtime/resources/web-docs-infoserver/js/jobmanagerFrontend.jshttps://github.com/stratosphere/stratosphere/pull/876/files#diff-0(4)

Patch Links:
- https://github.com/stratosphere/stratosphere/pull/876.patch
- https://github.com/stratosphere/stratosphere/pull/876.diff

—
Reply to this email directly or view it on
GitHubhttps://github.com/stratosphere/stratosphere/pull/876
.

**Comment by rmetzger** [comment]
Okay, I've tested your change but it does not seem to solve the issue.
See the attached screenshot: I can not read the number of finished tasks.

unreabable

**Comment by rmetzger** [comment]
One other thing: Do you have a ICLA signed with the Apache Software Foundation?
Since Stratosphere is moving into the Apache Software Foundation (As Apache Flink), you have to sign a ICLA and send it to ASF's secretary: https://www.apache.org/licenses/icla.pdf (See also: https://www.apache.org/licenses/)
The filled ICLA is not super pressing, but we can only merge the pull request, once this document is signed.

**Comment by vikhyat** [comment]
Sorry, I'd missed some other places where the same computation is repeated. Fixed the commit now.

I just signed the ICLA and sent it to ASF's secretary, I'm not sure how long it will take to process. I listed Apache Flink in the "notify project" field so I'm guessing you'll get a notification once it is processed.

**Comment by rmetzger** [comment]
Cool, thank you. I'll test your change again.

**Comment by rmetzger** [comment]
Okay. I can confirm that this pull request is working properly. Lets wait until ASF has notified us that the ICLA is available, then, we'll merge it (after the 0.5 release).

**Comment by vikhyat** [comment]
ICLA has been filed.

**Comment by rmetzger** [comment]
Okay, thank you. I'll merge the change soon.

**Comment by rmetzger** [comment]
Thank you @vikhyat for fixing the issue. I've merged your pull request in 73a9dcc92ae8911bfc7dd429fba78be6a63e3043.

**Pull request closed without merging**
