### PR TITLE
Functions can now implement ResultTypeQueryable to supply TypeInformation manually.

### PR DESCRIPTION
**Pull request by twalthr**
Implements #845.

### CODE REVIEW

**Comment by fhueske** [comment]
@atsikiridis This PR implements what you need to overcome the type erasure issue.

**Comment by atsikiridis** [comment]
Hello @fhueske , yes it works fine for the hadoop wrappers. Thanks @twalthr .

**Comment by StephanEwen** [comment]
I will merge this for 0.6 now. Several improvements depend on this.

**Comment by uce** [comment]
Merged in e3984986226b10796f0169b47f2480dd55ed3f74.

**Pull request closed without merging**
