### PR TITLE
Clean up LICENSE and NOTICE files

### PR DESCRIPTION
**Pull request by rmetzger**
This commit is from @uce.
1. Added LICENSE and NOTICE files to the source tree
   => we now have two files, one for the source, one for the dist
2. Renamed LICENSE.txt and NOTICE.txt without the .txt 
   => This seems to be the common naming.
3. Removed swt-visualization project, because it used LGPL 2.1 dependencies and nobody really uses it. (We do not support it)
4. Removed the notices about the usage of other Apache licensed SW, because I am not sure if we need it

### CODE REVIEW

**Comment by rmetzger** [comment]
I think we should keep the contents of the old NOTICE file.

**Comment by StephanEwen** [comment]
The old Notice file had an incomplete list of license dependencies. Ufuk's new LICENSE file has a complete list.

I'll add a note in the NOTICE file that a list of dependencies with their licenses is in the LICENSE file

**Comment by StephanEwen** [comment]
Merged in 551e83f8b04be549d5750477da814370e2def541 and 2d0975b028dc457f9b1f36bce6cb538a7d484967

**Comment by rmetzger** [comment]
Why did you merge it into `staging` ?
I though the branch is only for the new JavaAPI ?
Actually, `master` is kind of a staging area for releases. If we have the feeling that too many users are using `master` we should release a new version.

**Comment by fhueske** [comment]
The idea of the staging branch was to preserve the stability of the master branch, mainly because of the complex PR #545. @StephanEwen asked to do all PRs and merges against the staging branch to avoid merge conflicts when staging goes into master.
Once staging is merged with master, we will again work directly on master.

**Comment by rmetzger** [comment]
Oh, I got that wrong. I merged some PR's into `master` recently.

What's the problem with rebasing `staging` before merging it to master ?

I'm against having a `staging` branch. It makes our development process too complicated.
New features should be developed "somewhere" until they are stable enough, then, they should come into the mainline.
If the new Java API is not stable enough for `master` we should have kept it in @StephanEwen's repo  and make the pull requests there.

**Comment by fhueske** [comment]
The problem with rebasing staging is the hugh changelist by PR #545.
As I said, we will continue to work on master once staging is merged.

I think it's OK to have unstable new features in master but we should be careful with things that people are currently relying on (therefore the staging branch). 
What would be the difference of having a branch in @StephanEwen's repository (to which only he can commit) and a temp branch in the @stratosphere repository?

**Comment by StephanEwen** [comment]
It's only to avoid merge conflicts. We should merge staging tomorrow, if
Tobias' Tests work. Staging will then have existed for a week only.

Not all people were aware of the separate branch in my repo.

**Comment by rmetzger** [comment]
> What would be the difference of having a branch in @StephanEwen's repository (to which only he can commit)

That we follow a development process that most of the other open source projects follow. (Something like a design pattern)
The main repo only contains code that is considered stable and is reviewed.
Adding contributors to a repository is really easy ;) 
We could also create a separate repository in @stratosphere for the new Java API.

> We should merge staging tomorrow, if Tobias' Tests work.

Who is Tobias?

> Not all people were aware of the separate branch in my repo.

I understand. But there is an issue (https://github.com/stratosphere/stratosphere/issues/463) for planning the new Java API and you could have used that to promote your branch and find contributors. (Sorry, I don't want to annoy you. It is about reflecting our development process)

**Pull request closed without merging**
