### PR TITLE
Python interface for new API (Map/Reduce)

### PR DESCRIPTION
**Pull request by zentol**
#615

### CODE REVIEW

**Comment by zentol** [comment]
This PR now includes the flatMap-Operator aswell.

**Comment by zentol** [comment]
now includes CoGroup and Join.

**Comment by zentol** [comment]
now includes Filter/GroupReduce/Cross

**Comment by rmetzger** [comment]
Can you add an example that includes a complex machine learning algorithm written in python (but in a library, such as http://scikit-learn.org/stable/) ?
I'm asking for this since we want to allow our users to use the excellent algorithms available as python libraries.

**Comment by zentol** [comment]
I'll look into it.

**Comment by rmetzger** [comment]
I've merged the DistributedCache you are depending on (https://github.com/stratosphere/stratosphere/pull/564).

**Comment by zentol** [comment]
@rmetzger Can we add a more intuitive way to register these files? currently i have to write this:

```
Plan p = env.CreateProgramPlan();
p.registerCachedFile(path, "name");
PlanExecutor l = new Local-/RemoteExecutor();
l.executePlan(p);
```

whereas

```
env.registerCachedFile(path, "name");
env.execute();
```

would feel more in line with the new API.

**Comment by rmetzger** [comment]
Yeah, I think the DC is not really integrated with the new Java API. 
Can you do this integration and open a pull request?

**Comment by zentol** [comment]
sure.

**Comment by zentol** [comment]
updated the examples for the changes to the distributed cache.
the usability issue of having to create custom functions was solved with @twalthr help. turns out that curly braces are magical things.

instead of

```
public static class CustomPythonMap<Integer, String> extends PythonMap<Integer, String>{
...constructor stuff...
}

data.map(new CustomPythonMap(..))
```

you can just write

```
data.map(new PythonMap<Integer, String(..){})
```

**Comment by zentol** [comment]
I have uploaded the new version of the python interface.

Big changes:
- plans can be written completely in python (not every operation for environments/datasets are included yet though)
- the stratosphere package (including the protobuf package, which as a sideeffect blows up the additions/file count) are distributed automatically among the cluster (this is currently mandatory)

Small changes
- java side streamlined and uses threads
- functions implement the ResultTypeQueryable interface (no more curly braces!)

Questionable things (aka stuff that i need a confirmation for):
- The stratosphere python package will show up in the resource folder of the distribution. i needed a static place in order to run the python plan. I wonder if there is a more appropriate place.
- In order to get the path to the stratosphere package, i needed the location of the stratosphere distribution. for this i exported the STRATOSPHERE_ROOT_DIR variable in the scripts. (i guess i could use the already exported conf_dir variable and go from there, but that seems like jumping through hoops.)
- the protobuf package is now included in the distribution. it is licensed under http://opensource.org/licenses/BSD-3-Clause . Will this work? (and if it does, will i have to modify the licenses in the protobuf files in any way?)

This PR depends on:
#882

**Comment by uce** [comment]
The PR branch is on halt. @zentol will re-open in the new repo with the current state.

**Pull request closed without merging**
