### PR TITLE
Website updates

### PR DESCRIPTION
**Pull request by rmetzger**
Hi,

I changed "News" to "Blog", since I'm planning to write some posts with @uce.
Fabian requested to add another publication.
I also updated the google analytics code to the newest (official) version and used a different tracking id.

For some reason, the stratosphere.eu website is currently out of sync with the github repo! The Stratosphere-Event is missing!

I want approval from @ktzoumas on this before I publish it!

### CODE REVIEW

**Comment by fhueske** [comment]
Is there any good reason to switch the tracking ID? Won't we lose the previous stats?

**Comment by aalexandrov** [comment]
We don't know who has the account data for the previous ID.

**Comment by rmetzger** [comment]
No, there is no good reason ;) 
The last information I got was, that nobody knows the account owner ;)

**Comment by rmetzger** [comment]
Google Analytics now supports adding multiple administrators to a tracking ID. That's what I wanted to do with the new ID!

**Comment by fhueske** [comment]
a couple of people, including me :-D

2013/9/30 Alexander Alexandrov notifications@github.com

**Comment by rmetzger** [comment]
Can you add me with "View" -Permissions ?

**Comment by rmetzger** [comment]
Okay, I removed the commit

**Comment by fhueske** [comment]
I added you. Anybody else?

**Comment by asteriosk** [comment]
Please, add me as well. asteriosk@gmail.com

thanks,
Asterios

**Comment by ktzoumas** [comment]
Add me as well: kostas.tzoumas@gmail.com

The event is not there as I am waiting confirmation of the venue, this is
not a bug

Rest of the changes approved

Kostas

**Pull request merged**
