### PR TITLE
Add rCF() call to ContextEnvironment

### PR DESCRIPTION
**Pull request by zentol**
Addendum to #728.

### CODE REVIEW

**Comment by uce** [comment]
LGTM.

Your branch name is `dist-cache-fix`. What was the problem for the distributed cache here?

**Comment by zentol** [comment]
if you use the distributed cache via `ExecutionEnvironment.registerCachedFile()` it straight up doesn't work in an actual setting. When you submit a plan to stratosphere it seems to use `ContextEnvironment`, which until now never actually registered the files.

(Note that the version that #728 was supposed to replace does work)

```
Plan p = env.CreateProgramPlan();
p.registerCachedFile(path, "name");
PlanExecutor l = new Local-/RemoteExecutor();
l.executePlan(p);
```

**Comment by rmetzger** [comment]
So this is a bugfix that we should also add to 0.5.1 right?

**Comment by zentol** [comment]
yup

**Comment by StephanEwen** [comment]
The fix has been subsumed by abe88b7972c24b85338033042b07cba64ca91054

The above commit registers files in the `createProgramPlan()` method, which is the common point shared by all environments, etc.

**Pull request closed without merging**
