### PR TITLE
getAggregators() for SpargleIteration

### PR DESCRIPTION
**Pull request by markus-h**
See #704

### CODE REVIEW

**Comment by rmetzger** [comment]
I think this pull request is good to merge.

**Comment by rmetzger** [comment]
Can we merge this? An user is waiting for it, and its a trivial change.

**Comment by StephanEwen** [comment]
It is merged, tests are running.

**Comment by StephanEwen** [comment]
Merged in f65c65b32c36ed687a5e8beffee74b13772bea01

**Pull request closed without merging**
