### PR TITLE
Distinct Operator Implementation

### PR DESCRIPTION
**Pull request by markus-h**
See #760

### CODE REVIEW

**Comment by fhueske** [comment]
I know the distinct method headers have been there before, but I'm not sure if it makes sense to select keys for a distinct transformation. IMO, distinct should work on all fields of a tuple (or the full object to be more general).

**Comment by StephanEwen** [comment]
I think distinct with a subset of fields makes sense. Same thing is also
supported in SQL.

I would like this pull request to have some better unit tests. The current
ones simply try to see whether an exception is thrown.

**Comment by StephanEwen** [comment]
Have a look at the reduce translation tests and the reduce compiler tests.
They give you an idea how that works.

Also, duplicate elimination should be "combinable".

**Comment by fhueske** [comment]
I think we should also provide a `distinct` method without arguments that uses the full tuple or object for the distinct check. In that case we must make sure that all objects are comparable.

**Comment by markus-h** [comment]
Thanks for your feedback! I already included a plain distinct() method, that is currently only working for tuples and uses the full tuple.

**Comment by fhueske** [comment]
Cool, thanks! Had not noticed that one :smile:

**Comment by markus-h** [comment]
I added translation and compilation tests. Since the distinct operator currently is directly mapped to a groupReduce I almost had to copy the test from reduce.

**Comment by rmetzger** [comment]
Is this pull request ready to merge?

**Comment by uce** [comment]
Merged in e2aabd90604d5880ef8e7b82ce58de218ddd48a7.

Further comments I have are in [FLINK-984](https://issues.apache.org/jira/browse/FLINK-984).

**Pull request closed without merging**
