### PR TITLE
Rename Pregelsphere to Spargel (issue #310)

### PR DESCRIPTION
**Pull request by uce**
This is issue #310.

Renamed the BSP API of @StephanEwen (maven Module `pregelsphere` and packages `vertexcentric`) to Spargel (both Maven module and packages). Spargel is German for asparagus.

### CODE REVIEW

**Comment by uce** [comment]
I also wanted to add a test case, but had problems when adding `pact-tests` as a test-scoped dependency to the pom.

The test case is just an adoption of the existing ConnectedComponentsITCase to use `SpargelConnectedComponents` instead of `WorksetConnectedComponents`. If anyone has an idea what I am missing, I could add the extra commit here.

**Comment by StephanEwen** [comment]
Do we always want to rename the packages to "spargel"? We can keep the name Spargel for the project/feature, but call the packages "vertexcentric".

**Comment by rmetzger** [comment]
Why? Will there also be a "edgecentric" implementation?
I vote for renaming the packages as well.

**Comment by uce** [comment]
I think spargel as a package name is better from a user's perspective (aka I agree with @rmetzger).

**Comment by StephanEwen** [comment]
There is actually an "edgecentric" view, Vasia is implementing something
similar to that. There are also other possible views of graph processing,
such as matrix views, ...

**Comment by uce** [comment]
The last commit is a look into our bright feature without the name pact :sun_with_face:  @aljoscha will add the Scala API in `*.spargel.scala`.

**Comment by StephanEwen** [comment]
Merged in 696c8fe49dd644476014e9f1eea7c8832104efbb

**Pull request closed without merging**
