### PR TITLE
Remove unserializable fields in UserCodeObjectWrapper.java

### PR DESCRIPTION
**Pull request by aljoscha**
Completely change this. Add new ClosureCleaner that is based on the spark ClosureCleaner but does things a bit differently.

This one now checks whether fields it removes are actually accessed. In UserCodeObjectWrapper now throw an exception if the user code object contains non-serializable fields.

Does someone know what to do about the code-copying? Because I took this from spark.

### CODE REVIEW

**Comment by StephanEwen** [comment]
What do we actually gain here? Unnecessary serializable fields stay. Necessary non-serializable fields still crash the code and in a rather intransparent way, because users assume they have set the variable.

A clean solution would be to to an check about what fields are actually referenced and clean all others. If non-serializable fields remain, report an error.

**Comment by aljoscha** [comment]
Yes but I have bigger fish to fry right now, so I wanted this as a quick fix for some cases.

**Comment by StephanEwen** [comment]
I am a little worried that this makes problems hard to debug. If someone writes a program with a non-serializable data type in the closure, he does not get a nonserializable exception, but simply a null pointer at runtime. That is hard to trace back.

What do you think?

**Comment by aljoscha** [comment]
Completely new, read updated description.

**Comment by StephanEwen** [comment]
That is fine, if we handle the license correctly. Please make sure that:
- You write in the source file that it is in parts based on code from the spark project.
- You add to the NOTICE.txt file an entry for spark, similar to the ones that are in there.

**Comment by StephanEwen** [comment]
Please remember to update the NOTICE file.

**Comment by aljoscha** [comment]
Yes, yes, and also a notice in the code.

**Comment by StephanEwen** [comment]
Merged in 039c0829cfd0b7741feb881e865b91958032d9dc

**Comment by rmetzger** [comment]
I don't see a update in the NOTICE file: https://github.com/stratosphere/stratosphere/blob/master/stratosphere-dist/src/main/stratosphere-bin/NOTICE.txt

**Comment by rmetzger** [comment]
Why did you close the PR without any comment?
I still think my comment regarding the missing entry in the NOTICE file is valid.

**Comment by aljoscha** [comment]
I don't think I closed it on purpose. @StephanEwen said he wanted to merge anyways because of the restructuring. He could have just added the notice, though...

I didn't come around to adding it myself yet.

**Pull request closed without merging**
