### PR TITLE
Serializer fixes

### LINKED ISSUE #160: Scala Frontend: PactList Serialization Bug
I tried to reimplement the Java version of the ComputeEdgeDegree example as a Scala Pact program.
The job requires to return multiple records from a reducer (one per input record). However, currently the Scala reducer can only return a single record. I tried to solve this issue by returning a Scala list from the Reducer that contains all emitted records and to flat out that list using a flatMap. The Scala list seems to be correctly translated into the PactList type, but during its serialization a NullPointerException is raised.

The code of the failing Scala job is here:

https://github.com/fhueske/ozone/blob/fc914eadc3507cc27a2eb4891b3f491df0cb0e7a/pact-scala/pact-scala-examples/src/main/scala/eu/stratosphere/scala/examples/graph/ComputeEdgeDegrees2.scala

### PR DESCRIPTION
**Pull request by aljoscha**
This fixes #160

### CODE REVIEW

**Comment by aljoscha** [comment]
@fhueske I checked it with your code example in #160, it does indeed work now.

**Comment by fhueske** [comment]
:-D Thanks for the fix!

**Comment by aljoscha** [comment]
@rmetzger The travis build for this pull request is done and all tests passed as can be seen when clicking on the link here. Github, however, does not seem to notice. Could this be because of the move to stratosphere/stratosphere?

**Comment by rmetzger** [comment]
Okay, I'm going to ask the Travis guys tomorrow evening. (I don't have time sooner)

**Comment by rmetzger** [comment]
@aljoscha it seems that the Travis integration is working again.

**Pull request merged**
