### PR TITLE
Cleanup of main pom; generate javadocs

### PR DESCRIPTION
**Pull request by rmetzger**
Step 1 for https://github.com/stratosphere/stratosphere/issues/225

### CODE REVIEW

**Comment by physikerwelt** [comment]
+1

**Comment by StephanEwen** [comment]
I agree that a test coverage check is good. But when we reconfigure this, we would probably move to a newer version anyways and check the configuration.

I would vote to remove the old garbage from the pom and setup test coverage checks properly when we will re-introduce them.

**Comment by fhueske** [comment]
fair enough

**Comment by StephanEwen** [comment]
Merged in a8228ceb96bfba2b4b9d63ace8c77077a0689a7b

**Pull request closed without merging**
