### PR TITLE
Upload build SNAPSHOTS as tgz and as directory to DOPA server

### PR DESCRIPTION
**Pull request by rmetzger**
This pull request will extend Travis so that on every push into stratosphere/master, a `stratosphere-0-4-SNAPSHOT.tgz` will be uploaded into  http://dopa.dima.tu-berlin.de/bin/

This is helpful if users don't want to build the system on their own.

Travis builds the files anyways to we can just ssh them to that server.

### CODE REVIEW

**Comment by rmetzger** [comment]
I cancelled the test for the second commit manually. Is being executed from this branch https://travis-ci.org/stratosphere/stratosphere/builds/12843365 
I have to use a separate branch to test this because I'm not deploying anything from pull requests.

**Comment by rmetzger** [comment]
Please do not merge.

**Comment by rmetzger** [comment]
Okay. The pull request is ready to merge.

This is how the binaries will look like and where they are placed: http://dopa.dima.tu-berlin.de/bin/

**Comment by StephanEwen** [comment]
Manually merged in 9fef2778dde5c999e08144416bba9aa79dc74117

**Pull request closed without merging**
