### PR TITLE
Added K-Means Demo to Quickstart (Website)

### PR DESCRIPTION
**Pull request by rmetzger**
Preview: http://robertmetzger.de/stratosphere/quickstart/

Thanks to @fhueske for fixing the KMeans example and writing the python tool!

### CODE REVIEW

**Comment by uce** [comment]
Great idea!

Some suggestions:
- What about the following ordering on the quickstart page: Setup, **Example**, Java, Scala
- For the lead paragraph, I would remove the linebreak before "on the way"
- What about adding K-Means to the title (and other places) instead of just clustering
- The markdown markup (pun intended) is not working for `*relative standard deviation*`

**Comment by StephanEwen** [comment]
Beautiful. Like Ufuk said, some markup stuff is not working, bot otherwise,
I like it...

**Comment by rmetzger** [comment]
Thanks. I fixed the issues (I did not add k-means into the box on the quickstart page, but its in the text below).

**Comment by fhueske** [comment]
Some remarks:
- Since I changed the KMeans Job (added a data source, two operators, and a sink) you should update the screenshots of the web frontend that show the plan and the progress monitoring.
- The plots of the raw data have not the same size.

**Comment by rmetzger** [comment]
I updated the figures and merged it!

**Pull request closed without merging**
