### PR TITLE
Skip failing tests

### PR DESCRIPTION
**Pull request by physikerwelt**
Change-Id: I9d57cfd42913c47eb8551ae156c987fcd65459b7

see http://dopa-2.dima.tu-berlin.de:8080/job/ozone-build/61/ (from the dima subnet) for details.

### CODE REVIEW

**Comment by rmetzger** [comment]
Thank you for your pull request to Stratosphere / Ozone.

I can't access your link (and we'd like to be a transparent open source project), so I don't know if there is any discussion or explanation there.. 

There is already a pending pull request that fixes the failing test: https://github.com/dimalabs/ozone/pull/110

**Comment by physikerwelt** [comment]
Hi Robert,
I feel sorry for the restriction... I requested to open the ports for the Jenkins server more than 2 month ago... but TUbit is slow.
It would be nice, if the master branch would not have failing tests. This is further evidence that an open push model does not work.
Again...I'd vote for a combination of gerrit and jenkins... that's the way many large open source projects go.
Best Moritz

**Comment by sscdotopen** [comment]
which open source projects use this combination?

**Comment by physikerwelt** [comment]
e.g. typo3, mediawiki, 
http://en.wikipedia.org/wiki/Gerrit_(software)
https://wiki.jenkins-ci.org/pages/viewpage.action?pageId=58001258
I see that we don't want to run a public jenkins instance, since the modified junit test code is a major security risk. Anyhow, pushing something to a public master branch that does not pass the tests is not very helpful.

**Pull request closed without merging**
