### PR TITLE
BasicType-/BooleanComparator consistent comparison

### PR DESCRIPTION
**Pull request by zentol**
#761

### CODE REVIEW

**Comment by StephanEwen** [comment]
The current order is important to make sure that a requested ascending comparison is really ascending. If you switch the order in this one place, then a group order of ascending over boolean will no longer be a ascending, because the code assumes the current behavior.

**Comment by zentol** [comment]
This is actually a larger issue than i expected. for _any_ class extending from TypeComparator, or any of its subclasses, it is basically a coin flip how compareToReference is implemented. Even classes at the very top (for example the TupleComparator) can disagree.

**Comment by StephanEwen** [comment]
It may be that this comes from the fact that different people implemented those comparators. Since they are not yet tested, the build accepted the behavior.

To  fix this, have a look at the way the `RecordComparator` does it. That one is consistent with the way the runtime expects the behavior to correctly produce ascending/descending orders.

**Comment by zentol** [comment]
it seems like i made a mistake and created an issue were none actually exists. 

The TypeComparator.cTF() methods are fine. The BooleanComparator should be fixed though.

Turns out there are only 2 groups of Comparators that uses a different order than the TypeComparator, namely TupleComparators and a few in the test packages of runtime. 
Since the TupleComparators only delegate the comparisons to others, no change is necessary here. 
The ones used in the tests _could_ be changed, but i doubt its necessary.

**Comment by StephanEwen** [comment]
merged in 8e72db9f1935ce6ee063f5a23cbc544cc1dc3210

**Pull request closed without merging**
